(function () {
    'use strict';
    var conf = window.conf = window.conf || {};
    conf.levelData = [
        {
            pack: 'Alpha',
            level: [
                {
                    id: 'T1_Line',
                    index: '',
                    lines: '3',
                    moves: '3',
                    variants: '1',
                    title: 'Tutorial: Line Tool',
                    icon: 'lvl_t1__line_icon',
                    image: 'lvl_t1__line_detailed',
                    description: 'Construct a triangle with the given vertices. To create a segment or a line, select the Line tool and click on one point, then on another one.',
                    quote: 'The idealized ruler, known as a straightedge, is assumed to be infinite in length, and has no markings on it and only one edge.',
                    quote_author: 'Wikipedia'
                },
                {
                    id: 'T2_Circle',
                    index: '',
                    lines: '1',
                    moves: '1',
                    variants: '1',
                    title: 'Tutorial: Circle Tool',
                    icon: 'lvl_t2__circle_icon',
                    image: 'lvl_t2__circle_detailed',
                    description: 'Construct a circle with center O through the point P. Select the Circle tool and click on the center, then on any point of the circle.',
                    quote: 'Circles can only be drawn starting from two given points: the center and a point on the circle. The compass collapses when it is not drawing a circle.',
                    quote_author: 'Wikipedia'
                },
                {
                    id: 'T3_Point',
                    index: '',
                    lines: '0',
                    moves: '0',
                    variants: '1',
                    title: 'Tutorial: Point Tool',
                    icon: 'lvl_t3__point_icon',
                    image: 'lvl_t3__point_detailed',
                    description: 'Construct all the intersection points. Select the Point tool and click on the field to create a new point. Points are automatically stuck to the nearest intersection or line.',
                    quote: 'Euclid originally defined the point as "that which has no part".',
                    quote_author: 'Wikipedia'
                },
                {
                    id: 'TEquilateral',
                    index: '',
                    lines: '4',
                    moves: '4',
                    variants: '2',
                    title: 'Equilateral Triangle',
                    icon: 'lvl_t_equilateral_icon',
                    image: 'lvl_t_equilateral_detailed',
                    description: 'Construct an equilateral triangle with the given side. The construction must be exact. Guessing even very close points does not count as a solution.',
                    quote: 'All three angles of an equilateral triangle are always 60°.',
                    quote_author: 'Hint'
                },
                {
                    id: 'Angle60',
                    index: '1.1',
                    lines: '3',
                    moves: '3',
                    variants: '2',
                    title: 'Angle of 60°',
                    icon: 'lvl_angle60_icon',
                    image: 'lvl_angle60_detailed',
                    description: 'Construct an angle of 60° with the given side.',
                    quote: 'Let no one ignorant of geometry enter here.',
                    quote_author: 'Plato'
                },
                {
                    id: 'PerpBisector',
                    index: '1.2',
                    lines: '3',
                    moves: '3',
                    variants: '1',
                    title: 'Perpendicular Bisector',
                    icon: 'lvl_perp_bisector_icon',
                    image: 'lvl_perp_bisector_detailed',
                    description: 'Construct the perpendicular bisector of the segment.',
                    quote: 'Education is what remains after one has forgotten everything he learned in school.',
                    quote_author: 'Albert Einstein'
                },
                {
                    id: 'TPerpBisector',
                    index: '',
                    lines: '1',
                    moves: '3',
                    variants: '1',
                    title: 'Tutorial: Perpendicular Bisector',
                    icon: 'lvl_t_perp_bisector_icon',
                    image: 'lvl_t_perp_bisector_detailed',
                    description: 'You have discovered the Perpendicular Bisector tool. Click sequentially on two points to see how it works.',
                    quote: 'Note that the Perpendicular Bisector tool costs 3 elementary (E) moves.',
                    quote_author: 'Euclidea Manual'
                },
                {
                    id: 'Midpoint',
                    index: '1.3',
                    lines: '2',
                    moves: '4',
                    variants: '1',
                    title: 'Midpoint',
                    icon: 'lvl_midpoint_icon',
                    image: 'lvl_midpoint_detailed',
                    description: 'Construct the midpoint between two points.',
                    quote: 'Without geometry, life would be pointless.',
                    quote_author: 'Joke'
                },
                {
                    id: 'CircleInSquare',
                    index: '1.4',
                    lines: '3',
                    moves: '5',
                    variants: '1',
                    title: 'Circle in Square',
                    icon: 'lvl_circle_in_square_icon',
                    image: 'lvl_circle_in_square_detailed',
                    description: 'Inscribe a circle in the square.',
                    quote: 'You can\'t fit a round peg in a square hole.',
                    quote_author: 'American proverb'
                },
                {
                    id: 'RhombusInRect',
                    index: '1.5',
                    lines: '3',
                    moves: '5',
                    variants: '2',
                    title: 'Rhombus in Rectangle',
                    icon: 'lvl_rhombus_in_rect_icon',
                    image: 'lvl_rhombus_in_rect_detailed',
                    description: 'Inscribe a rhombus in the rectangle so that they share a diagonal.',
                    quote: 'Without mathematics there is no art.',
                    quote_author: 'Luca Pacioli'
                },
                {
                    id: 'CircleCenter',
                    index: '1.6',
                    lines: '2',
                    moves: '5',
                    variants: '1',
                    title: 'Circle Center',
                    icon: 'lvl_circle_center_icon',
                    image: 'lvl_circle_center_detailed',
                    description: 'Construct the center of the circle.',
                    quote: 'Nature is an infinite sphere of which the center is everywhere and the circumference nowhere.',
                    quote_author: 'Blaise Pascal'
                },
                {
                    id: 'SquareInCircle',
                    index: '1.7',
                    lines: '6',
                    moves: '7',
                    variants: '1',
                    title: 'Inscribed Square',
                    icon: 'lvl_square_in_circle_icon',
                    image: 'lvl_square_in_circle_detailed',
                    description: 'Inscribe a square in the circle. A vertex is given.',
                    quote: 'Where there is matter, there is geometry.',
                    quote_author: 'Johannes Kepler'
                }
            ]
        },
        {
            pack: 'Beta',
            level: [
                {
                    id: 'BisectAngle',
                    index: '2.1',
                    lines: '2',
                    moves: '4',
                    variants: '1',
                    title: 'Angle Bisector',
                    icon: 'lvl_bisect_angle_icon',
                    image: 'lvl_bisect_angle_detailed',
                    description: 'Construct the line that bisects the given angle.',
                    quote: 'The description of right lines and circles, upon which geometry is founded, belongs to mechanics. Geometry does not teach us to draw these lines, but requires them to be drawn.',
                    quote_author: 'Isaac Newton'
                },
                {
                    id: 'TBisectAngle',
                    index: '',
                    lines: '1',
                    moves: '4',
                    variants: '1',
                    title: 'Tutorial: Angle Bisector',
                    icon: 'lvl_t_bisect_angle_icon',
                    image: 'lvl_t_bisect_angle_detailed',
                    description: 'You have discovered the Angle Bisector tool. Click on any point on a side, on the vertex, and on any point on the other side.',
                    quote: 'Note that the Angle Bisector tool costs 4 elementary (E) moves.',
                    quote_author: 'Euclidea Manual'
                },
                {
                    id: 'RhombusInTriangle',
                    index: '2.2',
                    lines: '4',
                    moves: '9',
                    variants: '1',
                    title: 'Rhombus in Triangle',
                    icon: 'lvl_rhombus_in_triangle_icon',
                    image: 'lvl_rhombus_in_triangle_detailed',
                    description: 'Inscribe a rhombus in the triangle so that they share the common angle A.',
                    quote: 'The moving power of mathematical invention is not reasoning but imagination.',
                    quote_author: 'Augustus de Morgan'
                },
                {
                    id: 'Angle30',
                    index: '2.3',
                    lines: '3',
                    moves: '3',
                    variants: '2',
                    title: 'Angle of 30°',
                    icon: 'lvl_angle30_icon',
                    image: 'lvl_angle30_detailed',
                    description: 'Construct an angle of 30° with the given side.',
                    quote: 'Inspiration is needed in geometry, just as much as in poetry.',
                    quote_author: 'Alexander Pushkin'
                },
                {
                    id: 'DoubleAngle',
                    index: '2.4',
                    lines: '3',
                    moves: '3',
                    variants: '2',
                    title: 'Double Angle',
                    icon: 'lvl_double_angle_icon',
                    image: 'lvl_double_angle_detailed',
                    description: 'Construct an angle equal to the given one so that they share one side.',
                    quote: 'Contradiction is not a sign of falsity, nor the lack of contradiction a sign of truth.',
                    quote_author: 'Blaise Pascal'
                },
                {
                    id: 'CutRectangle',
                    index: '2.5',
                    lines: '3',
                    moves: '3',
                    variants: '1',
                    title: 'Cut Rectangle',
                    icon: 'lvl_cut_rectangle_icon',
                    image: 'lvl_cut_rectangle_detailed',
                    description: 'Construct a line through the given point that cuts the rectangle into two parts of equal area.',
                    quote: 'Measure twice, cut once!',
                    quote_author: 'Proverb'
                },
                {
                    id: 'DropPerp',
                    index: '2.6',
                    lines: '2',
                    moves: '3',
                    variants: '1',
                    title: 'Drop a Perpendicular',
                    icon: 'lvl_drop_perp_icon',
                    image: 'lvl_drop_perp_detailed',
                    description: 'Drop a perpendicular from the point to the line.',
                    quote: 'The knowledge of which geometry aims is the knowledge of the eternal.',
                    quote_author: 'Plato'
                },
                {
                    id: 'ErectPerp',
                    index: '2.7',
                    lines: '1',
                    moves: '3',
                    variants: '1',
                    title: 'Erect a Perpendicular',
                    icon: 'lvl_erect_perp_icon',
                    image: 'lvl_erect_perp_detailed',
                    description: 'Erect a perpendicular from the point on the line.',
                    quote: 'What we know is not much. What we do not know is immense.',
                    quote_author: 'Pierre-Simon Laplace'
                },
                {
                    id: 'TDropPerp',
                    index: '',
                    lines: '1',
                    moves: '3',
                    variants: '1',
                    title: 'Tutorial: Perpendicular',
                    icon: 'lvl_t_drop_perp_icon',
                    image: 'lvl_t_drop_perp_detailed',
                    description: 'You have discovered the Perpendicular tool. Click on the line, then on the point.',
                    quote: 'Note that the Perpendicular tool costs 3 elementary (E) moves.',
                    quote_author: 'Euclidea Manual'
                },
                {
                    id: 'Tangent1',
                    index: '2.8',
                    lines: '2',
                    moves: '3',
                    variants: '1',
                    title: 'Tangent to Circle at Point',
                    icon: 'lvl_tangent1_icon',
                    image: 'lvl_tangent1_detailed',
                    description: 'Construct a tangent to the circle at the given point.',
                    quote: 'If a man\'s wit be wandering, let him study the mathematics.',
                    quote_author: 'Francis Bacon'
                },
                {
                    id: 'CircleTangentL',
                    index: '2.9',
                    lines: '2',
                    moves: '4',
                    variants: '1',
                    title: 'Circle Tangent to Line',
                    icon: 'lvl_circle_tangent_l_icon',
                    image: 'lvl_circle_tangent_l_detailed',
                    description: 'Construct a circle with the given center that is tangent to the given line.',
                    quote: 'Intellectual labor in math lessons is the touchstone of thinking.',
                    quote_author: 'Vasili Sukhomlinsky'
                },
                {
                    id: 'CircleInRhombus',
                    index: '2.10',
                    lines: '4',
                    moves: '6',
                    variants: '1',
                    title: 'Сircle in Rhombus',
                    icon: 'lvl_circle_in_rhombus_icon',
                    image: 'lvl_circle_in_rhombus_detailed',
                    description: 'Inscribe a circle in the rhombus.',
                    quote: 'The mathematician\'s patterns, like the painter\'s or the poet\'s must be beautiful; the ideas like the colours or the words, must fit together in a harmonious way.',
                    quote_author: 'Godfrey Hardy'
                }
            ]
        },
        {
            pack: 'Gamma',
            level: [
                {
                    id: 'ChordMidpoint',
                    index: '3.1',
                    lines: '2',
                    moves: '4',
                    variants: '1',
                    title: 'Chord Midpoint',
                    icon: 'lvl_chord_midpoint_icon',
                    image: 'lvl_chord_midpoint_detailed',
                    description: 'Construct a chord whose midpoint is given.',
                    quote: 'The study of the mathematics, like the Nile, begins in minuteness, but ends in magnificence.',
                    quote_author: 'Charles Colton'
                },
                {
                    id: 'ATrByOrthocenter',
                    index: '3.2',
                    lines: '3',
                    moves: '6',
                    variants: '1',
                    title: 'Triangle by Angle and Orthocenter',
                    icon: 'lvl_a_tr_by_orthocenter_icon',
                    image: 'lvl_a_tr_by_orthocenter_detailed',
                    description: 'Construct a segment connecting the sides of the angle to get a triangle whose orthocenter is in the point O.',
                    quote: 'A mathematician is a machine for turning coffee into theorems.',
                    quote_author: 'Alfred Rényi'
                },
                {
                    id: 'ATrByCircumcenter',
                    index: '3.3',
                    lines: '2',
                    moves: '2',
                    variants: '1',
                    title: 'Intersection of Perpendicular Bisectors',
                    icon: 'lvl_a_tr_by_circumcenter_icon',
                    image: 'lvl_a_tr_by_circumcenter_detailed',
                    description: 'Construct a segment connecting the sides of the angle to get a triangle whose perpendicular bisectors are intersected in the point O.',
                    quote: 'Knowledge exists to be imparted.',
                    quote_author: 'Ralph Emerson.'
                },
                {
                    id: 'AEqualSegments1',
                    index: '3.4',
                    lines: '4',
                    moves: '6',
                    variants: '2',
                    title: 'Three equal segments - 1',
                    icon: 'lvl_a_equal_segments1_icon',
                    image: 'lvl_a_equal_segments1_detailed',
                    description: 'Given an angle ABC and a point M inside it, find points D on BA and E on BC and construct segments DM and ME such that BD = DM = ME.',
                    quote: 'All knowledge degenerates into probability.',
                    quote_author: 'David Hume'
                },
                {
                    id: 'CircleTangentPL',
                    index: '3.5',
                    lines: '3',
                    moves: '6',
                    variants: '1',
                    title: 'Circle through Point Tangent to Line',
                    icon: 'lvl_circle_tangent_p_l_icon',
                    image: 'lvl_circle_tangent_p_l_detailed',
                    description: 'Construct a circle through the point A that is tangent to the given line at the point B.',
                    quote: 'Knowledge comes, but wisdom lingers.',
                    quote_author: 'Alfred Tennyson'
                },
                {
                    id: 'TMove',
                    index: '',
                    lines: '0',
                    moves: '0',
                    variants: '1',
                    title: 'Tutorial: Move Tool',
                    icon: 'lvl_t_move_icon',
                    image: 'lvl_t_move_detailed',
                    description: 'Pascal\'s theorem states that if a hexagon is inscribed in a circle, then three points of intersection of its opposite sides lie on a straight line. Use the Move tool to see how the theorem works: just drag the blue points.',
                    quote: 'Our nature consists in motion; complete rest is death.',
                    quote_author: 'Blaise Pascal'
                },
                {
                    id: 'TrapezoidCut',
                    index: '3.6',
                    lines: '3',
                    moves: '5',
                    variants: '1',
                    title: 'Midpoints of Trapezoid Bases',
                    icon: 'lvl_trapezoid_cut_icon',
                    image: 'lvl_trapezoid_cut_detailed',
                    description: 'Construct a line passing through the midpoints of the trapezoid bases.',
                    quote: 'If there is a God, he is a great mathematician.',
                    quote_author: 'Paul Dirac'
                },
                {
                    id: 'Angle45',
                    index: '3.7',
                    lines: '2',
                    moves: '5',
                    variants: '2',
                    title: 'Angle of 45°',
                    icon: 'lvl_angle45_icon',
                    image: 'lvl_angle45_detailed',
                    description: 'Construct an angle of 45° with the given side.',
                    quote: 'He is unworthy of the name of man who is ignorant of the fact that the diagonal of a square is incommensurable with its side.',
                    quote_author: 'Plato'
                },
                {
                    id: 'Lozenge',
                    index: '3.8',
                    lines: '5',
                    moves: '7',
                    variants: '4',
                    title: 'Lozenge',
                    icon: 'lvl_lozenge_icon',
                    image: 'lvl_lozenge_detailed',
                    description: 'Construct a rhombus with the given side and an angle of 45° in a vertex.',
                    quote: 'To think deeply of simple things.',
                    quote_author: 'Arnold Ross'
                }
            ]
        },
        {
            pack: 'Delta',
            level: [
                {
                    id: 'CDoubleSeg',
                    index: '4.1',
                    lines: '3',
                    moves: '3',
                    variants: '2',
                    title: 'Double Segment',
                    icon: 'lvl_c_double_seg_icon',
                    image: 'lvl_c_double_seg_detailed',
                    description: 'Construct a point C on the line AB such that |AC|=2|AB| using only a compass.',
                    quote: 'A mathematical truth is neither simple nor complicated in itself, it is.',
                    quote_author: 'Emile Lemoine'
                },
                {
                    id: 'Angle60Drop',
                    index: '4.2',
                    lines: '3',
                    moves: '4',
                    variants: '2',
                    title: 'Angle of 60° - 2',
                    icon: 'lvl_angle60_drop_icon',
                    image: 'lvl_angle60_drop_detailed',
                    description: 'Construct a straight line through the given point that makes an angle of 60° with the given line.',
                    quote: 'The best angle from which to approach any problem is the try-angle.',
                    quote_author: 'Author Unknown'
                },
                {
                    id: 'EquilateralAboutCircle',
                    index: '4.3',
                    lines: '5',
                    moves: '6',
                    variants: '1',
                    title: 'Circumscribed Equilateral Triangle',
                    icon: 'lvl_equilateral_about_circle_icon',
                    image: 'lvl_equilateral_about_circle_detailed',
                    description: 'Construct an equilateral triangle that is circumscribed about the circle and contains the given point.',
                    quote: 'Logic is the anatomy of thought.',
                    quote_author: 'John Locke'
                },
                {
                    id: 'EquilateralInCircle',
                    index: '4.4',
                    lines: '5',
                    moves: '6',
                    variants: '1',
                    title: 'Equilateral Triangle in Circle',
                    icon: 'lvl_equilateral_in_circle_icon',
                    image: 'lvl_equilateral_in_circle_detailed',
                    description: 'Inscribe an equilateral triangle in the circle using the given point as a vertex. The center of the circle is not given.',
                    quote: 'We do not choose mathematics as our profession; it chooses us.',
                    quote_author: 'Yuri Manin'
                },
                {
                    id: 'TIntersect',
                    index: '',
                    lines: '0',
                    moves: '0',
                    variants: '1',
                    title: 'Tutorial: Intersect Tool',
                    icon: 'lvl_t_intersect_icon',
                    image: 'lvl_t_intersect_detailed',
                    description: 'If it is hard to hit the required intersection since lines are too close to each other, use the Intersect tool. Select one object (a circle or a line), then the second one. To practice, construct the intersection of the given circles.',
                    quote: 'Every intersection has a story.',
                    quote_author: 'Katherine Dunn'
                },
                {
                    id: 'Cut2Rectangles',
                    index: '4.5',
                    lines: '5',
                    moves: '5',
                    variants: '1',
                    title: 'Cut Two Rectangles',
                    icon: 'lvl_cut2_rectangles_icon',
                    image: 'lvl_cut2_rectangles_detailed',
                    description: 'Construct a line that cuts each of the rectangles into two parts of equal area.',
                    quote: 'Mathematics is the most reliable form of prophecy.',
                    quote_author: 'Wilhelm Schwebel'
                },
                {
                    id: 'Sqrt2',
                    index: '4.6',
                    lines: '3',
                    moves: '5',
                    variants: '1',
                    title: 'Square Root of 2',
                    icon: 'lvl_sqrt2_icon',
                    image: 'lvl_sqrt2_detailed',
                    description: 'Let |AB|=1. Construct a point C on the ray AB such that the length of AC is equal to the square root of 2.',
                    quote: 'The square root of 2 is also known as Pythagoras\' constant.',
                    quote_author: 'Wikipedia'
                },
                {
                    id: 'Sqrt3',
                    index: '4.7',
                    lines: '3',
                    moves: '3',
                    variants: '1',
                    title: 'Square Root of 3',
                    icon: 'lvl_sqrt3_icon',
                    image: 'lvl_sqrt3_detailed',
                    description: 'Let |AB|=1. Construct a point C on the ray AB such that the length of AC is equal to the square root of 3.',
                    quote: 'The square root of 3 is also known as Theodorus\' constant.',
                    quote_author: 'Wikipedia'
                },
                {
                    id: 'Angle15',
                    index: '4.8',
                    lines: '3',
                    moves: '5',
                    variants: '2',
                    title: 'Angle of 15°',
                    icon: 'lvl_angle15_icon',
                    image: 'lvl_angle15_detailed',
                    description: 'Construct an angle of 15° with the given side.',
                    quote: 'If we know anything we know it by mathematics.',
                    quote_author: 'Pierre Gassendi'
                },
                {
                    id: 'SquareByOppMidpoints',
                    index: '4.9',
                    lines: '6',
                    moves: '10',
                    variants: '1',
                    title: 'Square by Opposite Midpoints',
                    icon: 'lvl_square_by_opp_midpoints_icon',
                    image: 'lvl_square_by_opp_midpoints_detailed',
                    description: 'Construct a square, given two midpoints of opposite sides.',
                    quote: 'For the first condition to be fulfilled in Mathematics is to be exact; the second is to be as clear and simple as possible.',
                    quote_author: 'Lazare Carnot'
                },
                {
                    id: 'SquareByAdjMidpoints',
                    index: '4.10',
                    lines: '7',
                    moves: '10',
                    variants: '2',
                    title: 'Square by Adjacent Midpoints',
                    icon: 'lvl_square_by_adj_midpoints_icon',
                    image: 'lvl_square_by_adj_midpoints_detailed',
                    description: 'Construct a square, given two midpoints of adjacent sides.',
                    quote: 'Thinking is the hardest work there is, which is probably the reason so few engage in it.',
                    quote_author: 'Henry Ford'
                }
            ]
        },
        {
            pack: 'Epsilon',
            level: [
                {
                    id: 'Parallel',
                    index: '5.1',
                    lines: '2',
                    moves: '4',
                    variants: '1',
                    title: 'Parallel Line',
                    icon: 'lvl_parallel_icon',
                    image: 'lvl_parallel_detailed',
                    description: 'Construct a line parallel to the given line through the given point.',
                    quote: 'It is ignorance alone that could lead anyone to try to prove the axiom.',
                    quote_author: 'Aristotle'
                },
                {
                    id: 'TParallel',
                    index: '',
                    lines: '1',
                    moves: '4',
                    variants: '1',
                    title: 'Tutorial: Parallel Line',
                    icon: 'lvl_t_parallel_icon',
                    image: 'lvl_t_parallel_detailed',
                    description: 'You have discovered the Parallel tool. Click on the line, then on the point.',
                    quote: 'Note that the Parallel tool costs 4 elementary (E) moves.',
                    quote_author: 'Euclidea Manual'
                },
                {
                    id: 'Parallelogram3V',
                    index: '5.2',
                    lines: '4',
                    moves: '8',
                    variants: '3',
                    title: 'Parallelogram by Three Vertices',
                    icon: 'lvl_parallelogram3_v_icon',
                    image: 'lvl_parallelogram3_v_detailed',
                    description: 'Construct a parallelogram whose three of four vertices are given.',
                    quote: 'Logic is invincible, because in order to combat logic it is necessary to use logic.',
                    quote_author: 'Pierre Boutroux'
                },
                {
                    id: 'LineAlongPoints',
                    index: '5.3',
                    lines: '2',
                    moves: '4',
                    variants: '1',
                    title: 'Line Equidistant from Two Points - 1',
                    icon: 'lvl_line_along_points_icon',
                    image: 'lvl_line_along_points_detailed',
                    description: 'Construct a line through the point C and at equal distance from the points A and B but that does not pass between them.',
                    quote: 'Mathematics is a tool for reasoning.',
                    quote_author: 'Richard Feynman'
                },
                {
                    id: 'LineBetweenPoints',
                    index: '5.4',
                    lines: '3',
                    moves: '5',
                    variants: '1',
                    title: 'Line Equidistant from Two Points - 2',
                    icon: 'lvl_line_between_points_icon',
                    image: 'lvl_line_between_points_detailed',
                    description: 'Construct a line through the point C that goes between the points A and B and that is at equal distance from them.',
                    quote: 'Mathematics is the science of those things that are clear in and of themselves.',
                    quote_author: 'Carl Jacobi'
                },
                {
                    id: 'TrapezoidMedian',
                    index: '5.5',
                    lines: '2',
                    moves: '6',
                    variants: '1',
                    title: 'Arithmetic Mean of Trapezoid Bases',
                    icon: 'lvl_trapezoid_median_icon',
                    image: 'lvl_trapezoid_median_detailed',
                    description: 'Construct a line segment that is parallel to the bases of the trapezoid and whose length is equal to the arithmetic mean of their length.',
                    quote: 'Mathematics is the language with which God wrote the universe.',
                    quote_author: 'Galileo Galilei'
                },
                {
                    id: 'Hash',
                    index: '5.6',
                    lines: '2',
                    moves: '4',
                    variants: '2',
                    title: 'Hash',
                    icon: 'lvl_hash_icon',
                    image: 'lvl_hash_detailed',
                    description: 'Construct a line through the given point on which two pairs of parallel lines cut off equal line segments.',
                    quote: 'No other science than mathematics strengthens so much our faith in the power of the human mind.',
                    quote_author: 'Hugo Steinhaus'
                },
                {
                    id: 'ShiftAngle',
                    index: '5.7',
                    lines: '2',
                    moves: '6',
                    variants: '1',
                    title: 'Shift Angle',
                    icon: 'lvl_shift_angle_icon',
                    image: 'lvl_shift_angle_detailed',
                    description: 'Construct an angle from the given point that is equal to the given angle so that their sides are parallel.',
                    quote: 'Geometry is the real life.',
                    quote_author: 'Oscar Zariski'
                },
                {
                    id: 'SquareAboutCircle',
                    index: '5.8',
                    lines: '6',
                    moves: '11',
                    variants: '1',
                    title: 'Circumscribed Square',
                    icon: 'lvl_square_about_circle_icon',
                    image: 'lvl_square_about_circle_detailed',
                    description: 'Circumscribe a square about the circle. Two its sides should be parallel to the given line.',
                    quote: 'A round man cannot be expected to fit in a square hole right away. He must have time to modify his shape.',
                    quote_author: 'Mark Twain'
                },
                {
                    id: 'SquareInSquare',
                    index: '5.9',
                    lines: '6',
                    moves: '7',
                    variants: '1',
                    title: 'Square in Square',
                    icon: 'lvl_square_in_square_icon',
                    image: 'lvl_square_in_square_detailed',
                    description: 'Inscribe a square in the square. A vertex is given.',
                    quote: 'If you wish to learn swimming you have to go into the water and if you wish to become a problem solver you have to solve problems.',
                    quote_author: 'George Pólya'
                },
                {
                    id: 'HexagonBySide',
                    index: '5.10',
                    lines: '7',
                    moves: '8',
                    variants: '2',
                    title: 'Regular Hexagon',
                    icon: 'lvl_hexagon_by_side_icon',
                    image: 'lvl_hexagon_by_side_detailed',
                    description: 'Construct a regular hexagon with the given side.',
                    quote: 'If only I had the theorems! Then I should find the proofs easily enough.',
                    quote_author: 'Bernard Riemann'
                }
            ]
        },
        {
            pack: 'Zeta',
            level: [
                {
                    id: 'PtSymmetry',
                    index: '6.1',
                    lines: '4',
                    moves: '5',
                    variants: '1',
                    title: 'Point Reflection',
                    icon: 'lvl_pt_symmetry_icon',
                    image: 'lvl_pt_symmetry_detailed',
                    description: 'Reflect the segment across the point.',
                    quote: 'Symmetry is one of the ideas by which man through the ages has tried to comprehend and create order, beauty, and perfection.',
                    quote_author: 'Hermann Weyl'
                },
                {
                    id: 'MirrorSeg',
                    index: '6.2',
                    lines: '5',
                    moves: '5',
                    variants: '1',
                    title: 'Reflection',
                    icon: 'lvl_mirror_seg_icon',
                    image: 'lvl_mirror_seg_detailed',
                    description: 'Reflect the segment across the line.',
                    quote: 'Symmetry is what we see at a glance; based on the fact that there is no reason for any difference...',
                    quote_author: 'Blaise Pascal'
                },
                {
                    id: 'ShiftSegment',
                    index: '6.3',
                    lines: '3',
                    moves: '4',
                    variants: '2',
                    title: 'Copy Segment',
                    icon: 'lvl_shift_segment_icon',
                    image: 'lvl_shift_segment_detailed',
                    description: 'Construct a segment from the given point that is equal to the given segment and lies on the same line with it.',
                    quote: 'Let no man who is not a Mathematician read the elements of my work.',
                    quote_author: 'Leonardo da Vinci'
                },
                {
                    id: 'GivenAngleBisector',
                    index: '6.4',
                    lines: '4',
                    moves: '4',
                    variants: '1',
                    title: 'Given Angle Bisector',
                    icon: 'lvl_given_angle_bisector_icon',
                    image: 'lvl_given_angle_bisector_detailed',
                    description: 'Construct two straight lines through the two given points respectively so that the given line is a bisector of the angle that they make.',
                    quote: 'I would live to study, and not study to live.',
                    quote_author: 'Francis Bacon'
                },
                {
                    id: 'CircleByRadius',
                    index: '6.5',
                    lines: '4',
                    moves: '5',
                    variants: '1',
                    title: 'Non-collapsing Compass',
                    icon: 'lvl_circle_by_radius_icon',
                    image: 'lvl_circle_by_radius_detailed',
                    description: 'Construct a circle with the given center and the radius equal to the length of the given segment.',
                    quote: 'There is nothing strange in the circle being the origin of any and every marvel.',
                    quote_author: 'Aristotle'
                },
                {
                    id: 'TCircleByRadius',
                    index: '',
                    lines: '1',
                    moves: '5',
                    variants: '1',
                    title: 'Tutorial: Non-collapsing Compass',
                    icon: 'lvl_t_circle_by_radius_icon',
                    image: 'lvl_t_circle_by_radius_detailed',
                    description: 'You have discovered the Non-collapsing Compass tool. Click on two points to set the radius length, then on the center of the circle.',
                    quote: 'Note that the Compass tool costs 5 elementary (E) moves.',
                    quote_author: 'Euclidea Manual'
                },
                {
                    id: 'TranslateSegment',
                    index: '6.6',
                    lines: '2',
                    moves: '6',
                    variants: '2',
                    title: 'Translate Segment',
                    icon: 'lvl_translate_segment_icon',
                    image: 'lvl_translate_segment_detailed',
                    description: 'Construct a segment from the given point parallel and equal to the given segment.',
                    quote: 'Mathematics is a game played according to certain rules with meaningless marks on paper.',
                    quote_author: 'David Hilbert'
                },
                {
                    id: 'TriangleBySides',
                    index: '6.7',
                    lines: '4',
                    moves: '12',
                    variants: '4',
                    title: 'Triangle by Three Sides',
                    icon: 'lvl_triangle_by_sides_icon',
                    image: 'lvl_triangle_by_sides_detailed',
                    description: 'Construct a triangle with the side AB and the two other sides equal to the given segments.',
                    quote: 'One geometry cannot be more true than another; it can only be more convenient.',
                    quote_author: 'Henri Poincaré'
                },
                {
                    id: 'HypotenuseAndLeg',
                    index: '6.8',
                    lines: '5',
                    moves: '9',
                    variants: '4',
                    title: 'Hypotenuse and Leg',
                    icon: 'lvl_hypotenuse_and_leg_icon',
                    image: 'lvl_hypotenuse_and_leg_detailed',
                    description: 'Construct a right triangle with the given hypotenuse AB and whose leg is equal to the given segment.',
                    quote: 'The best way to make mathematics interesting to students and laymen is to approach it in a spirit of play.',
                    quote_author: 'Martin Gardner'
                },
                {
                    id: 'ParallelogramBySP',
                    index: '6.9',
                    lines: '5',
                    moves: '8',
                    variants: '1',
                    title: 'Parallelogram',
                    icon: 'lvl_parallelogram_by_s_p_icon',
                    image: 'lvl_parallelogram_by_s_p_detailed',
                    description: 'Construct a parallelogram with the given side and the midpoint of the opposite side in the given point.',
                    quote: 'The subject of mathematics is so serious that nobody should miss an opportunity to make it a little bit entertaining.',
                    quote_author: 'Blaise Pascal'
                }
            ]
        },
        {
            pack: 'Eta',
            level: [
                {
                    id: 'SumSquares',
                    index: '7.1',
                    lines: '3',
                    moves: '6',
                    variants: '1',
                    title: 'Sum of Areas of Squares',
                    icon: 'lvl_sum_squares_icon',
                    image: 'lvl_sum_squares_detailed',
                    description: 'Construct a square whose area equals the sum of the areas of the two given squares and all three have the common angle.',
                    quote: 'The whole is greater than the sum of its parts.',
                    quote_author: 'Aristotle'
                },
                {
                    id: 'Annulus',
                    index: '7.2',
                    lines: '4',
                    moves: '5',
                    variants: '1',
                    title: 'Annulus',
                    icon: 'lvl_annulus_icon',
                    image: 'lvl_annulus_detailed',
                    description: 'Construct a circle that is concentric with the given one and divides it into 2 parts of equal area.',
                    quote: 'We must know, we will know!',
                    quote_author: 'David Hilbert'
                },
                {
                    id: 'Angle75',
                    index: '7.3',
                    lines: '4',
                    moves: '5',
                    variants: '2',
                    title: 'Angle of 75°',
                    icon: 'lvl_angle75_icon',
                    image: 'lvl_angle75_detailed',
                    description: 'Construct an angle of 75° with the given side.',
                    quote: 'The human mind has first to construct forms, independently, before we can find them in things.',
                    quote_author: 'Albert Einstein'
                },
                {
                    id: 'Equidistant3',
                    index: '7.4',
                    lines: '3',
                    moves: '7',
                    variants: '3',
                    title: 'Line Equidistant from Three Points',
                    icon: 'lvl_equidistant3_icon',
                    image: 'lvl_equidistant3_detailed',
                    description: 'Construct a line that is at equal distance from the given three points.',
                    quote: 'Mathematics is gymnastics of thinking.',
                    quote_author: 'Alexander Suvorov'
                },
                {
                    id: 'Heron',
                    index: '7.5',
                    lines: '4',
                    moves: '4',
                    variants: '1',
                    title: 'Heron\'s Problem',
                    icon: 'lvl_heron_icon',
                    image: 'lvl_heron_detailed',
                    description: 'Construct a point C and segments AC and BC such that the sum of their length is minimal.',
                    quote: 'Life is good for only two things, discovering mathematics and teaching mathematics.',
                    quote_author: 'Simeon Poisson'
                },
                {
                    id: 'Circle3',
                    index: '7.6',
                    lines: '3',
                    moves: '7',
                    variants: '1',
                    title: 'Circumscribed Circle',
                    icon: 'lvl_circle3_icon',
                    image: 'lvl_circle3_detailed',
                    description: 'Construct the circumcircle of the triangle.',
                    quote: 'I should almost therefore put forward the proposal that the third hypothesis (angle sum of a triangle less than two right angles) holds on the surface of an imaginary sphere.',
                    quote_author: 'Johann Lambert'
                },
                {
                    id: 'CircleInTriangle',
                    index: '7.7',
                    lines: '4',
                    moves: '8',
                    variants: '1',
                    title: 'Inscribed Circle',
                    icon: 'lvl_circle_in_triangle_icon',
                    image: 'lvl_circle_in_triangle_detailed',
                    description: 'Construct the incircle of the triangle.',
                    quote: 'Circles to square and cubes to double would give a man exercise trouble.',
                    quote_author: 'Matthew Prior'
                },
                {
                    id: 'AngleMidpoint',
                    index: '7.8',
                    lines: '3',
                    moves: '5',
                    variants: '1',
                    title: 'Segment by Midpoint',
                    icon: 'lvl_angle_midpoint_icon',
                    image: 'lvl_angle_midpoint_detailed',
                    description: 'Construct a segment with the ends on the sides of the angle such that the given point is its midpoint.',
                    quote: 'Do not worry about your difficulties in Mathematics: I can assure you mine are far greater.',
                    quote_author: 'Albert Einstein'
                },
                {
                    id: 'AngleIsosceles',
                    index: '7.9',
                    lines: '2',
                    moves: '5',
                    variants: '1',
                    title: 'Angle Isosceles',
                    icon: 'lvl_angle_isosceles_icon',
                    image: 'lvl_angle_isosceles_detailed',
                    description: 'Construct a line through the given point such that it cuts off equal segments on the sides of the angle.',
                    quote: 'There are two ways to do great mathematics. The first is to be smarter than everybody else. The second way is to be stupider than everybody else — but persistent.',
                    quote_author: 'Raoul Bott'
                },
                {
                    id: 'AngleTrisection54',
                    index: '7.10',
                    lines: '4',
                    moves: '5',
                    variants: '1',
                    title: 'Angle 54° Trisection',
                    icon: 'lvl_angle_trisection54_icon',
                    image: 'lvl_angle_trisection54_detailed',
                    description: 'Construct two rays that divide the given angle of 54° into three equal parts.',
                    quote: 'If I feel unhappy, I do mathematics to become happy. If I am happy, I do mathematics to keep happy.',
                    quote_author: 'Alfred Rényi'
                },
                {
                    id: 'Excircle',
                    index: '7.11',
                    lines: '4',
                    moves: '8',
                    variants: '3',
                    title: 'Excircle',
                    icon: 'lvl_excircle_icon',
                    image: 'lvl_excircle_detailed',
                    description: 'Construct an excircle of the triangle formed by the three given lines.',
                    quote: 'It is easy to go from the house of reality to the forest of mathematics, but only few know how to go back.',
                    quote_author: 'Hugo Steinhaus'
                },
                {
                    id: 'PerimeterBisector',
                    index: '7.12',
                    lines: '4',
                    moves: '7',
                    variants: '3',
                    title: 'Perimeter Bisector',
                    icon: 'lvl_perimeter_bisector_icon',
                    image: 'lvl_perimeter_bisector_detailed',
                    description: 'Construct a straight line through a vertex of the triangle that divides its perimeter in half.',
                    quote: 'He became a poet, he lacked imagination for a mathematician.',
                    quote_author: 'David Hilbert'
                }
            ]
        },
        {
            pack: 'Theta',
            level: [
                {
                    id: 'AMinPerimeter',
                    index: '8.1',
                    lines: '6',
                    moves: '6',
                    variants: '1',
                    title: 'Minimum Perimeter - 1',
                    icon: 'lvl_a_min_perimeter_icon',
                    image: 'lvl_a_min_perimeter_detailed',
                    description: 'Construct a triangle whose perimeter is the minimum possible whose vertices lie on the two sides of the angle and the third vertex is in the point A.',
                    quote: 'Geometry is frozen music.',
                    quote_author: 'Johann Goethe'
                },
                {
                    id: '3rdProportional',
                    index: '8.2',
                    lines: '3',
                    moves: '3',
                    variants: '1',
                    title: 'Third Proportional',
                    icon: 'lvl_3rd_proportional_icon',
                    image: 'lvl_3rd_proportional_detailed',
                    description: 'Construct a point D on the ray such that the segment AD is the third proportional to the given line segments.',
                    quote: 'Everything around us is geometry.',
                    quote_author: 'Le Corbusier'
                },
                {
                    id: 'TrapezoidHarmMean',
                    index: '8.3',
                    lines: '3',
                    moves: '5',
                    variants: '1',
                    title: 'Harmonic Mean of Trapezoid Bases',
                    icon: 'lvl_trapezoid_harm_mean_icon',
                    image: 'lvl_trapezoid_harm_mean_detailed',
                    description: 'Construct a line segment that is parallel to the bases of the trapezoid and whose length is equal to the harmonic mean of their length.',
                    quote: 'Mathematics is less knowledge than skill.',
                    quote_author: 'Philip Davis'
                },
                {
                    id: 'LDropPerp',
                    index: '8.4',
                    lines: '5',
                    moves: '5',
                    variants: '1',
                    title: 'Drop a Perpendicular*',
                    icon: 'lvl_l_drop_perp_icon',
                    image: 'lvl_l_drop_perp_detailed',
                    description: 'Drop a perpendicular from the point to the line passing through the center of the circle using only a straightedge.',
                    quote: 'It is not enough to have a good mind. The main thing is to use it well.',
                    quote_author: 'Rene Descartes'
                },
                {
                    id: 'LMidpoint',
                    index: '8.5',
                    lines: '5',
                    moves: '5',
                    variants: '1',
                    title: 'Midpoint*',
                    icon: 'lvl_l_midpoint_icon',
                    image: 'lvl_l_midpoint_detailed',
                    description: 'Construct the midpoint of the segment using only a straightedge. To help you, a line parallel to the segment is given.',
                    quote: 'Everything should be made as simple as possible, but not simpler.',
                    quote_author: 'Albert Einstein'
                },
                {
                    id: 'InteriorAngles',
                    index: '8.6',
                    lines: '2',
                    moves: '4',
                    variants: '2',
                    title: 'Interior Angles',
                    icon: 'lvl_interior_angles_icon',
                    image: 'lvl_interior_angles_detailed',
                    description: 'Construct a line through the point that crosses the two lines so that the interior angles are equal.',
                    quote: 'I am ever more convinced that the necessity of our (Euclidean) geometry cannot be proved — at least not by human reason for human reason.',
                    quote_author: 'Carl Friedrich Gauss'
                },
                {
                    id: 'OctagonBySide',
                    index: '8.7',
                    lines: '9',
                    moves: '13',
                    variants: '2',
                    title: 'Regular Octagon',
                    icon: 'lvl_octagon_by_side_icon',
                    image: 'lvl_octagon_by_side_detailed',
                    description: 'Construct a regular octagon with the given side.',
                    quote: 'The essence of mathematics is its freedom.',
                    quote_author: 'Georg Cantor'
                },
                {
                    id: 'TrapezoidCut3',
                    index: '8.8',
                    lines: '3',
                    moves: '6',
                    variants: '2',
                    title: 'Trisection by Trapezoid Diagonals',
                    icon: 'lvl_trapezoid_cut3_icon',
                    image: 'lvl_trapezoid_cut3_detailed',
                    description: 'Construct a line segment that is parallel to the bases of the trapezoid and is divided to three equal parts by its diagonals.',
                    quote: 'It is hard to convince a high-school student that he will encounter a lot of problems more difficult than those of algebra and geometry.',
                    quote_author: 'Edgar Watson Howe'
                },
                {
                    id: 'OrthicTriangle',
                    index: '8.9',
                    lines: '6',
                    moves: '8',
                    variants: '1',
                    title: 'Minimum Perimeter - 2',
                    icon: 'lvl_orthic_triangle_icon',
                    image: 'lvl_orthic_triangle_detailed',
                    description: 'Inscribe a triangle into the given whose perimeter is the minimum possible.',
                    quote: 'The roots of education are bitter, but the fruit is sweet.',
                    quote_author: 'Aristotle'
                },
                {
                    id: 'HarmonicMean',
                    index: '8.10',
                    lines: '4',
                    moves: '4',
                    variants: '1',
                    title: 'Harmonic Mean of Segments',
                    icon: 'lvl_harmonic_mean_icon',
                    image: 'lvl_harmonic_mean_detailed',
                    description: 'Construct a point on the given ray to get a segment with length equal to the harmonic mean of the two adjacent segments.',
                    quote: 'Geometry is knowledge of the eternally existent.',
                    quote_author: 'Pythagoras'
                },
                {
                    id: 'ATrByCentroid',
                    index: '8.11',
                    lines: '5',
                    moves: '7',
                    variants: '1',
                    title: 'Triangle by Angle and Centroid',
                    icon: 'lvl_a_tr_by_centroid_icon',
                    image: 'lvl_a_tr_by_centroid_detailed',
                    description: 'Construct a segment connecting the sides of the angle to get a triangle whose centroid is in the point O.',
                    quote: 'I think, therefore I am.',
                    quote_author: 'Rene Descartes'
                }
            ]
        },
        {
            pack: 'Iota',
            level: [
                {
                    id: 'Tangent',
                    index: '9.1',
                    lines: '4',
                    moves: '5',
                    variants: '2',
                    title: 'Tangent of Circle',
                    icon: 'lvl_tangent_icon',
                    image: 'lvl_tangent_detailed',
                    description: 'Construct a tangent to the circle from the external point.',
                    quote: 'Nothing is more important than to see the sources of invention which are, in my opinion more interesting than the inventions themselves.',
                    quote_author: 'Gottfried Leibniz'
                },
                {
                    id: 'OuterTangent',
                    index: '9.2',
                    lines: '6',
                    moves: '8',
                    variants: '2',
                    title: 'Outer Tangent',
                    icon: 'lvl_outer_tangent_icon',
                    image: 'lvl_outer_tangent_detailed',
                    description: 'Construct an outer tangent between two circles.',
                    quote: 'It is the glory of geometry that from so few principles, fetched from without, it is able to accomplish so much.',
                    quote_author: 'Isaac Newton'
                },
                {
                    id: 'InnerTangent',
                    index: '9.3',
                    lines: '6',
                    moves: '8',
                    variants: '2',
                    title: 'Inner Tangent',
                    icon: 'lvl_inner_tangent_icon',
                    image: 'lvl_inner_tangent_detailed',
                    description: 'Construct an inner tangent between two circles.',
                    quote: 'Imagination is more important than knowledge.',
                    quote_author: 'Albert Einstein'
                },
                {
                    id: '90RotationCCW',
                    index: '9.4',
                    lines: '5',
                    moves: '9',
                    variants: '1',
                    title: 'Rotation 90°',
                    icon: 'lvl_90_rotation_c_c_w_icon',
                    image: 'lvl_90_rotation_c_c_w_detailed',
                    description: 'Rotate the line segment 90° counterclockwise about the given point.',
                    quote: 'Imagination decides everything.',
                    quote_author: 'Blaise Pascal'
                },
                {
                    id: '60RotationCW',
                    index: '9.5',
                    lines: '4',
                    moves: '4',
                    variants: '1',
                    title: 'Rotation 60°',
                    icon: 'lvl_60_rotation_c_w_icon',
                    image: 'lvl_60_rotation_c_w_detailed',
                    description: 'Rotate the line segment 60° clockwise about the given point.',
                    quote: 'Science is simply common sense at its best.',
                    quote_author: 'Thomas Huxley'
                },
                {
                    id: 'Divide3',
                    index: '9.6',
                    lines: '5',
                    moves: '6',
                    variants: '1',
                    title: 'Segment Trisection',
                    icon: 'lvl_divide3_icon',
                    image: 'lvl_divide3_detailed',
                    description: 'Construct two points that divide the segment into 3 equal parts.',
                    quote: 'Three Rules of Work: Out of clutter find simplicity; From discord find harmony; In the middle of difficulty lies opportunity.',
                    quote_author: 'Albert Einstein'
                },
                {
                    id: 'LDivide3',
                    index: '9.7',
                    lines: '8',
                    moves: '8',
                    variants: '1',
                    title: 'Segment Trisection*',
                    icon: 'lvl_l_divide3_icon',
                    image: 'lvl_l_divide3_detailed',
                    description: 'Construct points that divide the segment into three equal parts using only a straightedge. To help you, a line parallel to the segment is given.',
                    quote: 'Beauty is the first test: there is no permanent place in the world for ugly mathematics.',
                    quote_author: 'Godfrey Hardy'
                },
                {
                    id: 'Chord3',
                    index: '9.8',
                    lines: '3',
                    moves: '4',
                    variants: '2',
                    title: 'Chord Trisection',
                    icon: 'lvl_chord3_icon',
                    image: 'lvl_chord3_detailed',
                    description: 'Construct a chord of the larger circle through the given point that is divided into three equal segments by the smaller circle.',
                    quote: 'Mathematics is the door and key to the sciences.',
                    quote_author: 'Roger Bacon'
                },
                {
                    id: 'Segment6',
                    index: '9.9',
                    lines: '4',
                    moves: '5',
                    variants: '2',
                    title: 'Ratio 1 to 5',
                    icon: 'lvl_segment6_icon',
                    image: 'lvl_segment6_detailed',
                    description: 'Construct a point on the line segment that divides it in the ratio 1 : 5.',
                    quote: 'In mathematics the art of proposing a question must be held of higher value than solving it.',
                    quote_author: 'Georg Cantor'
                },
                {
                    id: '3CirclesC',
                    index: '9.10',
                    lines: '7',
                    moves: '10',
                    variants: '1',
                    title: 'Three Circles - 1',
                    icon: 'lvl_3_circles_c_icon',
                    image: 'lvl_3_circles_c_detailed',
                    description: 'Construct three circles with the given centers that are externally tangent each other.',
                    quote: 'Knowledge is power.',
                    quote_author: 'Francis Bacon'
                },
                {
                    id: 'Secant2',
                    index: '9.11',
                    lines: '4',
                    moves: '5',
                    variants: '2',
                    title: 'Secant Bisection',
                    icon: 'lvl_secant2_icon',
                    image: 'lvl_secant2_detailed',
                    description: 'Construct a secant through the given point that is divided into two equal segments by the circle.',
                    quote: 'Knowledge is light and ignorance is darkness.',
                    quote_author: 'Proverb'
                },
                {
                    id: '3CirclesI',
                    index: '9.12',
                    lines: '9',
                    moves: '14',
                    variants: '1',
                    title: 'Three Circles - 2',
                    icon: 'lvl_3_circles_i_icon',
                    image: 'lvl_3_circles_i_detailed',
                    description: 'Construct three circles tangent to each other at the given points.',
                    quote: 'Education is the best provision for the journey to old age.',
                    quote_author: 'Aristotle'
                }
            ]
        },
        {
            pack: 'Kappa',
            level: [
                {
                    id: '4thProportional',
                    index: '10.1',
                    lines: '2',
                    moves: '3',
                    variants: '1',
                    title: 'Fourth Proportional',
                    icon: 'lvl_4th_proportional_icon',
                    image: 'lvl_4th_proportional_detailed',
                    description: 'Construct a point D on the ray OC such that the segment OD is the fourth proportional to the given segments.',
                    quote: 'Mathematics is concerned only with the enumeration and comparison of relations.',
                    quote_author: 'Friedrich Gauss'
                },
                {
                    id: 'GeometricMean',
                    index: '10.2',
                    lines: '3',
                    moves: '5',
                    variants: '1',
                    title: 'Geometric Mean of Segments',
                    icon: 'lvl_geometric_mean_icon',
                    image: 'lvl_geometric_mean_detailed',
                    description: 'Construct a point on the given ray to get a segment with length equal to the geometric mean of two adjacent segments.',
                    quote: 'Mathematics is the part of physics where experiments are cheap.',
                    quote_author: 'Vladimir Arnold'
                },
                {
                    id: 'GoldenSection',
                    index: '10.3',
                    lines: '4',
                    moves: '5',
                    variants: '2',
                    title: 'Golden Section',
                    icon: 'lvl_golden_section_icon',
                    image: 'lvl_golden_section_detailed',
                    description: 'Construct a point that divides the segment in the "golden section".',
                    quote: 'The Golden ratio has inspired thinkers of all disciplines like no other number in the history of mathematics.',
                    quote_author: 'Mario Livio'
                },
                {
                    id: 'Angle54',
                    index: '10.4',
                    lines: '5',
                    moves: '6',
                    variants: '2',
                    title: 'Angle of 54°',
                    icon: 'lvl_angle54_icon',
                    image: 'lvl_angle54_detailed',
                    description: 'Construct an angle of 54° with the given side.',
                    quote: 'The scientist is not a person who gives the right answers, he\'s one who asks the right questions.',
                    quote_author: 'Claude Levi-Strauss'
                },
                {
                    id: 'L3Parallel',
                    index: '10.5',
                    lines: '7',
                    moves: '7',
                    variants: '1',
                    title: 'Third Parallel Line',
                    icon: 'lvl_l3_parallel_icon',
                    image: 'lvl_l3_parallel_detailed',
                    description: 'Construct a line through the given point that is parallel to the two given parallel lines using only a straightedge.',
                    quote: 'It is impossible to be a mathematician without being a poet in soul.',
                    quote_author: 'Sofia Kovalevskaya'
                },
                {
                    id: 'CircleInAngle',
                    index: '10.6',
                    lines: '6',
                    moves: '11',
                    variants: '2',
                    title: 'Circle in Angle',
                    icon: 'lvl_circle_in_angle_icon',
                    image: 'lvl_circle_in_angle_detailed',
                    description: 'Construct a circle through the given point that is tangent to both sides of the angle.',
                    quote: 'The mathematical sciences particularly exhibit order symmetry and limitations; and these are the greatest forms of the beautiful.',
                    quote_author: 'Aristotle'
                },
                {
                    id: 'TrapezoidGeomMean',
                    index: '10.7',
                    lines: '6',
                    moves: '9',
                    variants: '1',
                    title: 'Geometric Mean of Trapezoid Bases',
                    icon: 'lvl_trapezoid_geom_mean_icon',
                    image: 'lvl_trapezoid_geom_mean_detailed',
                    description: 'Construct a line segment that is parallel to the bases of the trapezoid and whose length is equal to the geometric mean of their length.',
                    quote: 'Mathematics is a language plus reasoning; it is like a language plus logic.',
                    quote_author: 'Richard Feynman'
                },
                {
                    id: 'Pentagon',
                    index: '10.8',
                    lines: '9',
                    moves: '10',
                    variants: '1',
                    title: 'Regular Pentagon',
                    icon: 'lvl_pentagon_icon',
                    image: 'lvl_pentagon_detailed',
                    description: 'Construct a regular pentagon inscribed in the circle. A vertex is given.',
                    quote: 'Mighty is geometry; joined with art, resistless.',
                    quote_author: 'Euripides'
                },
                {
                    id: 'Angle3',
                    index: '10.9',
                    lines: '6',
                    moves: '7',
                    variants: '2',
                    title: 'Angle of 3°',
                    icon: 'lvl_angle3_icon',
                    image: 'lvl_angle3_detailed',
                    description: 'Construct an angle of 3° with the given side.',
                    quote: 'Like all other sciences, mathematics arose out of the needs of men: from the measurement of land and the content of vessels, from the computation of time and from mechanics.',
                    quote_author: 'Friedrich Engels'
                }
            ]
        },
        {
            pack: 'Lambda',
            level: [
                {
                    id: 'TriangleByMidpoints',
                    index: '11.1',
                    lines: '5',
                    moves: '8',
                    variants: '1',
                    title: 'Triangle by Midpoints',
                    icon: 'lvl_triangle_by_midpoints_icon',
                    image: 'lvl_triangle_by_midpoints_detailed',
                    description: 'Construct a triangle given the midpoints of its sides.',
                    quote: '"Obvious" is the most dangerous word in mathematics.',
                    quote_author: 'Eric Bell'
                },
                {
                    id: 'TrBySideAndCentroid',
                    index: '11.2',
                    lines: '6',
                    moves: '7',
                    variants: '1',
                    title: 'Triangle by Side and Centroid',
                    icon: 'lvl_tr_by_side_and_centroid_icon',
                    image: 'lvl_tr_by_side_and_centroid_detailed',
                    description: 'Construct a triangle with the given side and centroid.',
                    quote: 'You are the only person on earth who can use your ability. It\'s an awesome responsibility.',
                    quote_author: 'Zig Ziglar'
                },
                {
                    id: 'TrByAltitudeBases',
                    index: '11.3',
                    lines: '5',
                    moves: '11',
                    variants: '1',
                    title: 'Triangle by Altitude Base Points',
                    icon: 'lvl_tr_by_altitude_bases_icon',
                    image: 'lvl_tr_by_altitude_bases_detailed',
                    description: 'Construct a triangle whose altitude base points are given.',
                    quote: 'One quickly realizes that simplicity and geometry are the language of timelessness and universality.',
                    quote_author: 'Paul Rand'
                },
                {
                    id: 'TrByIncircleBases',
                    index: '11.4',
                    lines: '6',
                    moves: '11',
                    variants: '1',
                    title: 'Triangle by Tangent Points',
                    icon: 'lvl_tr_by_incircle_bases_icon',
                    image: 'lvl_tr_by_incircle_bases_detailed',
                    description: 'Construct a triangle with the three given points where its incircle touches its sides.',
                    quote: 'Music is the arithmetic of sounds as optics is the geometry of light.',
                    quote_author: 'Claude Debussy'
                },
                {
                    id: 'TrByExcircleCenters',
                    index: '11.5',
                    lines: '9',
                    moves: '11',
                    variants: '1',
                    title: 'Triangle by Excenters',
                    icon: 'lvl_tr_by_excircle_centers_icon',
                    image: 'lvl_tr_by_excircle_centers_detailed',
                    description: 'Construct a triangle with the given excenters.',
                    quote: 'There are no sects in geometry.',
                    quote_author: 'Voltaire'
                },
                {
                    id: 'RTrBy2SidePoints',
                    index: '11.6',
                    lines: '6',
                    moves: '8',
                    variants: '2',
                    title: 'Right Triangle by Two Points on Legs',
                    icon: 'lvl_r_tr_by2_side_points_icon',
                    image: 'lvl_r_tr_by2_side_points_detailed',
                    description: 'Inscribe a right triangle into the circle so that the two given points lie on its two legs respectively. The center of the circle is in the point O.',
                    quote: 'Beauty is geometry.',
                    quote_author: 'Joanne Rowling'
                }
            ]
        },
        {
            pack: 'Mu',
            level: [
                {
                    id: 'CircleTangentCL',
                    index: '12.1',
                    lines: '4',
                    moves: '9',
                    variants: '2',
                    title: 'Circle Tangent to Line and Circle',
                    icon: 'lvl_circle_tangent_c_l_icon',
                    image: 'lvl_circle_tangent_c_l_detailed',
                    description: 'Construct a circle tangent to the line at the given point and to the given circle.',
                    quote: 'The object of mathematical rigor is to sanction and legitimize the conquests of intuition.',
                    quote_author: 'Jacques Hadamard'
                },
                {
                    id: 'Equilateral3',
                    index: '12.2',
                    lines: '7',
                    moves: '8',
                    variants: '2',
                    title: 'Equilateral Triangle - 2',
                    icon: 'lvl_equilateral3_icon',
                    image: 'lvl_equilateral3_detailed',
                    description: 'Construct an equilateral triangle whose one vertex is given and two others lie on the two parallel lines.',
                    quote: 'The only thing I am interested in using mathematics for is to have a good time and to help others do the same.',
                    quote_author: 'Paul Lockhart'
                },
                {
                    id: 'SquareInTriangle',
                    index: '12.3',
                    lines: '6',
                    moves: '12',
                    variants: '1',
                    title: 'Square in Triangle',
                    icon: 'lvl_square_in_triangle_icon',
                    image: 'lvl_square_in_triangle_detailed',
                    description: 'Inscribe a square in the acute triangle ABC so that one of its sides lies on AC.',
                    quote: 'The line of life is a ragged diagonal between duty and desire.',
                    quote_author: 'William Alger'
                },
                {
                    id: 'Equidistant2',
                    index: '12.4',
                    lines: '5',
                    moves: '8',
                    variants: '2',
                    title: 'Point Equidistant from Side of Angle and Point',
                    icon: 'lvl_equidistant2_icon',
                    image: 'lvl_equidistant2_detailed',
                    description: 'Given an angle ABC and a point M inside it, find points D on BA and E on BC and construct segments MD and DE of equal length so that DE is perpendicular to BC.',
                    quote: 'You can\'t criticize geometry. It\'s never wrong.',
                    quote_author: 'Paul Rand'
                },
                {
                    id: 'CircleTangentCC',
                    index: '12.5',
                    lines: '4',
                    moves: '8',
                    variants: '2',
                    title: 'Circle Tangent to Two Circles',
                    icon: 'lvl_circle_tangent_c_c_icon',
                    image: 'lvl_circle_tangent_c_c_detailed',
                    description: 'Construct a circle that is tangent to the two given circles and touches one of them in the given point.',
                    quote: 'There is still a difference between something and nothing, but it is purely geometrical and there is nothing behind the geometry.',
                    quote_author: 'Martin Gardner'
                },
                {
                    id: 'CircleTangentPPL',
                    index: '12.6',
                    lines: '6',
                    moves: '10',
                    variants: '2',
                    title: 'Circle Through Two Points and Tangent to Line',
                    icon: 'lvl_circle_tangent_p_p_l_icon',
                    image: 'lvl_circle_tangent_p_p_l_detailed',
                    description: 'Construct a circle that goes through the two given points and that is tangent to the given line.',
                    quote: 'The very smallest errors in mathematical matters are not to be neglected.',
                    quote_author: 'Isaac Newton'
                },
                {
                    id: 'RTrByHypAndTangentPt',
                    index: '12.7',
                    lines: '6',
                    moves: '9',
                    variants: '2',
                    title: 'Triangle by Tangent Point on Hypotenuse',
                    icon: 'lvl_r_tr_by_hyp_and_tangent_pt_icon',
                    image: 'lvl_r_tr_by_hyp_and_tangent_pt_detailed',
                    description: 'Construct a right triangle with the given hypotenuse and the tangent point of its incircle.',
                    quote: 'Since we cannot know all that there is to be known about anything, we ought to know a little about everything.',
                    quote_author: 'Blaise Pascal'
                }
            ]
        },
        {
            pack: 'Nu',
            level: [
                {
                    id: 'CMidpoint',
                    index: '13.1',
                    lines: '6',
                    moves: '6',
                    variants: '1',
                    title: 'Midpoint*',
                    icon: 'lvl_c_midpoint_icon',
                    image: 'lvl_c_midpoint_detailed',
                    description: 'Construct the midpoint between the given points using only a compass.',
                    quote: 'Don\'t spoil my circles!',
                    quote_author: 'Archimedes'
                },
                {
                    id: 'CTranslateCircle',
                    index: '13.2',
                    lines: '4',
                    moves: '4',
                    variants: '1',
                    title: 'Copy Circle',
                    icon: 'lvl_c_translate_circle_icon',
                    image: 'lvl_c_translate_circle_detailed',
                    description: 'Construct a circle with the given center that is equal to the given circle.',
                    quote: 'Nothing new had been done in Logic since Aristotle!',
                    quote_author: 'Kurt Godel'
                },
                {
                    id: 'CIntersectCL',
                    index: '13.3',
                    lines: '4',
                    moves: '4',
                    variants: '1',
                    title: 'Line-Circle Intersection',
                    icon: 'lvl_c_intersect_c_l_icon',
                    image: 'lvl_c_intersect_c_l_detailed',
                    description: 'Construct the intersection of the circle and the line defined by the two given points using only a compass.',
                    quote: 'A mathematician, like a painter or a poet, is a maker of patterns. If his patterns are more permanent than theirs, it is because they are made with ideas.',
                    quote_author: 'Godfrey Hardy'
                },
                {
                    id: 'EqualSegments3',
                    index: '13.4',
                    lines: '7',
                    moves: '7',
                    variants: '1',
                    title: 'Three Equal Segments',
                    icon: 'lvl_equal_segments3_icon',
                    image: 'lvl_equal_segments3_detailed',
                    description: 'Construct a segment whose ends lie on the sides of the angle such that three marked segments are equal.',
                    quote: 'We do not know a truth without knowing its cause.',
                    quote_author: 'Aristotle'
                },
                {
                    id: 'LTangent',
                    index: '13.5',
                    lines: '8',
                    moves: '8',
                    variants: '2',
                    title: 'Tangent to Circle*',
                    icon: 'lvl_l_tangent_icon',
                    image: 'lvl_l_tangent_detailed',
                    description: 'Construct a tangent to the circle from the external point using only a straightedge. The center of the circle is not given.',
                    quote: 'Projective geometry is all geometry.',
                    quote_author: 'Arthur Cayley'
                },
                {
                    id: 'Napoleon',
                    index: '13.6',
                    lines: '6',
                    moves: '6',
                    variants: '1',
                    title: 'Napoleon\'s Problem',
                    icon: 'lvl_napoleon_icon',
                    image: 'lvl_napoleon_detailed',
                    description: 'Construct the center of the given circle using only a compass.',
                    quote: 'The advancement and perfection of mathematics are intimately connected with the prosperity of the state.',
                    quote_author: 'Napoléon Bonaparte'
                },
                {
                    id: 'LDropPerp2',
                    index: '13.7',
                    lines: '10',
                    moves: '10',
                    variants: '1',
                    title: 'Drop a Perpendicular**',
                    icon: 'lvl_l_drop_perp2_icon',
                    image: 'lvl_l_drop_perp2_detailed',
                    description: 'Drop a perpendicular from the center of the circle to the given line using only a straightedge.',
                    quote: 'The only way to get at the truth about our imaginations is to use our imaginations, and that is hard work.',
                    quote_author: 'Paul Lockhart'
                },
                {
                    id: 'CIntersectX',
                    index: '13.8',
                    lines: '9',
                    moves: '9',
                    variants: '1',
                    title: 'Line-Circle Intersection*',
                    icon: 'lvl_c_intersect_x_icon',
                    image: 'lvl_c_intersect_x_detailed',
                    description: 'Construct the intersection of the circle and the line that goes through its center and the given point using only a compass.',
                    quote: 'Do not ask whether a statement is true until you know what it means.',
                    quote_author: 'Errett Bishop'
                },
                {
                    id: 'CircleTangentCPwCenterL',
                    index: '13.9',
                    lines: '8',
                    moves: '9',
                    variants: '2',
                    title: 'Circle with Center on Line',
                    icon: 'lvl_circle_tangent_c_pw_center_l_icon',
                    image: 'lvl_circle_tangent_c_pw_center_l_detailed',
                    description: 'Construct a circle with the center on the given line so that it passes through the given point and tangent to the given circle.',
                    quote: 'A mind is a fire to be kindled, not a vessel to be filled.',
                    quote_author: 'Plutarch'
                }
            ]
        }
    ];
}());